theme: jekyll-theme-cayman
title: Ivy League+ Pre-health Society
email: rifatislam85@gmail.com
description: >- 
  To connect and network with other students from top universities who want
  to pursue a career in health, medicine, and research. Students will hear
  from renowned and distinguished speakers, learn about health and research
  related opportunities, and receive personalized mentorship.
